language: bash
services:
  - docker

env:
  - APP=dnsmasq            VERSION=
  - APP=apache-hadoop-hdfs VERSION=2.7.3

before_script:
  - cd $APP/$VERSION
  - image="djx339/$APP:${VERSION:-latest}"

script:
  - docker build -t "$image" .

after_script:
  - docker images

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push ${image}
  - if [ "$APP" == "apache-hadoop-hdfs" ]; then
      bash ${TRAVIS_BUILD_DIR}/apache-hadoop-hdfs/$VERSION/test.sh;
    fi



# vim:set et ts=2 sw=2:
