language: bash
service: docker

env:
  - APP=dnsmasq            VERSION=
  - APP=apache-hadoop-hdfs VERSION=2.7.3

before_script:
  - env | sort
  - cd $APP/$VERSION
  - image="djx339/$app:${VERSION:-latest}"

script:
  - docker build -t "$image" .

after_script:
  - docker images



# vim:set et ts=2 sw=2:
