version: '2'

services:
  master:
    image: djx339/apache-hadoop-hdfs:2.7.3
    command: namenode
    environment:
      - MASTER=master
      - DNSSERVER=dnsserver
    depends_on:
      - nameserver
    links:
      - nameserver:dnsserver
    dns:
      - dnsserver
    hostname: master
    stdin_open: true
    tty: true
    restart: always
  slave:
    image: djx339/apache-hadoop-hdfs:2.7.3
    command: datanode
    environment:
      - DNSSERVER=dnsserver
      - MASTER=master
    depends_on:
      - nameserver
      - master
    links:
      - nameserver:dnsserver
    dns:
      - dnsserver
    stdin_open: true
    tty: true
    restart: always
  nameserver:
    image: djx339/dnsmasq
